# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "cc81c566417dd96d4f5152758aa7ddde"
name = "oddballs-subs-changeover"
application_url = "https://oddballs-subs-changeover.gadget.app/api/shopify/install-or-render"
embedded = true

[auth]
redirect_urls = [ "https://oddballs-subs-changeover.gadget.app/api/connections/auth/shopify/callback" ]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "https://webhooks.gadget-services.net/shopify/v1?domain=oddballs-subs-changeover.gadget.app"
topics = [ "shop/update", "app/uninstalled" ]
